apiVersion: batch/v1
kind: CronJob
metadata:
  name: gbfs-cronjob
  namespace: default
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gbfs-metrics  # Add this label here
        spec:
          containers:
          - name: gbfs-data-fetch
            image: manojsiriparthi/gbfs-data:latest
            env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            resources:
              limits:
                memory: "512Mi"
                cpu: "500m"
              requests:
                memory: "256Mi"
                cpu: "250m"
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
