apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  username: bWFub2o=             
  password: TWFub2oyNjI3
  host: Z2Jmcy1teXNxbC1kYi5jM3M4cW1pcTYwancuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==  

